name: Build Custom War Package

on:
  push:
    branches:
      - 2.204.4

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download CWP
        run: |
          curl https://repo.jenkins-ci.org/list/releases/io/jenkins/tools/custom-war-packager/custom-war-packager-cli/2.0-alpha-2/custom-war-packager-cli-2.0-alpha-2-jar-with-dependencies.jar -o custom-war-packager-cli.jar

      - name: Generate jenkins.war
        run: |
          java -jar custom-war-packager-cli.jar -configPath=jenkins-zh.yaml -version=2.204.4 -tmpDir=tmp

      - name: Upload to bintray
        run: |
          curl -T tmp/output/target/jenkins-zh-2.204.4.war -ulinuxsuren:${{ secrets.BINTRAY_TOKEN }} \
            -H "X-Bintray-Package:jenkins" -H "X-Bintray-Version:2.204.4" \
            https://api.bintray.com/content/jenkins-zh/generic/jenkins/2.204.4/jenkins-zh.war
          curl -X POST -ulinuxsuren:${{ secrets.BINTRAY_TOKEN }} https://api.bintray.com/content/jenkins-zh/generic/jenkins/2.224/publish
