name: Build & Push

on:
  push:
    branches:
      - 2.221

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker Publish
        run: |
          NEW_TAG="2.221"
          docker login docker.pkg.github.com --username LinuxSuRen --password ${{ secrets.GITHUB_TOKEN }}
          docker build . -t docker.pkg.github.com/jenkins-zh/docker-zh/jenkins-zh:$NEW_TAG
          docker push docker.pkg.github.com/jenkins-zh/docker-zh/jenkins-zh:$NEW_TAG
